name: .NET UI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest   # GitHub-hosted Linux VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run BDD tests
        run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
      
      # OPTIONAL: Generate LivingDoc from Reqnroll / SpecFlow execution
      - name: Generate LivingDoc Report
        run: |
          dotnet tool install --global databinding.LivingDoc.Report.CLI
          livingdocreport -f TestResults/TestExecution.json -o TestResults/GoogleSearchReport.html
        if: always()

      - name: Upload LivingDoc Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: livingdoc-report
          path: TestResults/GoogleSearchReport.html
